openapi: 3.0.1
info:
  title: Maraquser
  description: 'This is a RBAC project.'
  contact:
    name: Jamie Ynonan
    email: jamiea31@gmail.com
    url: https://github.com/JamieYnonan
  license:
    name: MIT
    url: https://github.com/JamieYnonan/maraquser/blob/master/LICENSE
  version: beta
servers:
  - url: http://{domain}/v1
    description: The local API server
    variables:
      domain:
        default: local.api.maraquser.maraquya.com
tags:
  - name: permission
    description: An approval of a mode of access to a resource
  - name: role
    description: A role that contains permissions
  - name: user
    description: A user of the system
paths:
  /permissions:
    $ref: 'paths/permission/permissions.yaml'
  /permissions/{permissionId}:
    $ref: 'paths/permission/permissionsById.yaml'
  /roles:
    $ref: 'paths/role/roles.yaml'
  /roles/{roleId}:
    $ref: 'paths/role/rolesById.yaml'
  /roles/{roleId}/permissions:
    $ref: 'paths/role/permission.yaml'
  /users:
    $ref: 'paths/user/users.yaml'
  /users/{userId}:
    $ref: 'paths/user/usersById.yaml'
  /users/token:
    $ref: 'paths/user/token.yaml'

components:
  schemas:
    Permission:
      $ref: 'schemas/permission/permission.yaml'
    Role:
      $ref: 'schemas/role/role.yaml'
    User:
      $ref: 'schemas/user/user.yaml'
    Token:
      $ref: 'schemas/user/token.yaml'
    Response:
      $ref: 'schemas/response.yaml'