version: '2'

services:
  mysql:
    image: mysql:5.7
    container_name: mu_mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
  redis:
    image: redis:4.0
    container_name: mu_redis
    volumes:
      - ./redis/data:/data
    ports:
      - "6379:6379"
  rabbit:
    image: rabbitmq:3.7-management
    container_name: mu_rabbit
    hostname: rabbit_maraquser
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_VHOST=maraquser
    volumes:
      - ./rabbit/data:/var/lib/rabbitmq
  maraquser:
    image: mu_app
    container_name: maraquser
    volumes:
      - ../app/:/app/:rw
      - ./log/nginx:/var/log/nginx/
      - ./log/php:/var/log/php-fpm/7.2
    ports:
      - "80:80"
    links:
      - mysql
      - rabbit
      - redis