version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - api

  rabbit:
    image: rabbitmq:3.7-management
    hostname: mu_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - api
      - worker
    environment:
      - HOSTNAME=mu_rabbit
      - RABBITMQ_NODENAME=rabbit@mu_rabbit
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_VHOST=maraquser
    volumes:
      - ./rabbit/data:/var/lib/rabbitmq/

  api:
    image: ${API_IMAGE}
    environment:
      - APP_DEBUG=${APP_DEBUG}
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.4"
          memory: 100M
      restart_policy:
        condition: on-failure
    volumes:
      - ../app/:/app/:rw
    ports:
      - "80:80"
    networks:
      - api
    depends_on:
      - mysql
      - rabbit
      - redis

  workers:
    image: mu_worker
    volumes:
      - ../workers/:/workers/:rw
      - ./worker/wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    depends_on:
      - rabbit
    command: bash -c  "wait-for-it.sh maraquser_rabbit:15672 && python /workers/welcome.py"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 20M
        reservations:
          cpus: '0.05'
          memory: 15M
      restart_policy:
        condition: on-failure
    networks:
      - worker

networks:
  api:
  worker:
