user:
  properties:
    email:
      - NotBlank: ~
      - Type:
        type: integer
    password:
      - NotBlank: ~
      - Type:
        type: string
    role_id:
      - NotBlank: ~
      - Type:
        type: string
